### PR TITLE
Remove Taobao

### LINKED ISSUE #79: Completely wrong site for Taobao
**What's the product you'd like PrivacySpy to add?**
Taobao's policy uses [this](https://www.taobaonline.com/privacy-policy/) site, which is not related to the Chinese company refrenced in the policy [here](https://world.taobao.com/).

**Where is the product's privacy policy? (Give a URL.)**
https://www.taobao.com/helpcenter/content/help_rule_policy_en.html

**Have you considered adding this product yourself?**
I may or may not update this to reflect keeping the old privacy policy for the respective site, as well as adding the actual Taobao to PrivacySpy. I am fine with someone else taking this if I don't get to it right away.

### PR DESCRIPTION
**Pull request by ibarakaiev**
**Type of pull request:** Product removal

**Related issues:** Closes #79.

---

This PR is in response to the linked issue. I couldn't find an English version of Taobao's privacy policy that's older than 2003, so it's better to just remove it from PrivacySpy altogether so as to not confuse our users. Alternatively, we could rename it to Taobao Online, but it doesn't even appear on Alexa Rank, so I don't think anyone would benefit from having Taobao Online on the website.

### CODE REVIEW

**Review by doamatto — APPROVED** [review]
Although I’d prefer we replace it with the proper policy, this technically is fine to merge

**Comment by ibarakaiev** [comment]
@doamatto me too, but I wasn't able to find it unfortunately.

**Comment by doamatto** [comment]
Oh, I linked to it in the issue. [Here it is again, though](https://www.taobao.com/helpcenter/content/help_rule_policy_en.html)

**Comment by ibarakaiev** [comment]
Yeah I found it separately as well, but it was last amended in 2003, so unless they really didn't update for 18 years I think there should probably be a newer one.

**Pull request merged**
