### PR TITLE
Updated Apple

### PR DESCRIPTION
**Pull request by doamatto**
**Type of pull request:** Product edit

---

Changes:
- Added self as a contributor
- Added hostnames for iCloud and Shazam (both fall under the same privacy policy)
- Added proper citation, note, and value for data breach response.

### CODE REVIEW

**Review by milesmcc — APPROVED** [review]

**Comment by milesmcc** [comment]
Looks good to me! Thanks doamatto.

**Comment by ibarakaiev** [comment]
Why don't we add Shazam and iCloud as separate products?

**Comment by doamatto** [comment]
It would be ideal to do something similar to Google's page where it shows affected products.

image

But both Shazam and iCloud (Dark Sky as well, I forgot to mention it) redirect to Apple's privacy policy, as Apple owns all 3 of them.

**Comment by ibarakaiev** [comment]
What I meant by adding them as separate products is exactly what you showed in the screenshot. That way they will be listed in PrivacySpy's directory (and the browser extension will show their names and descriptions instead of just "Apple"), and their product pages will redirect back to Apple (and Apple will list them as "Affected Products").

**Comment by doamatto** [comment]
Then yea; I agree that it should be handled that way. If you can point me in the way of how to set that up, I can make a PR for it

**Pull request merged**
