### PR TITLE
Import legacy products

### PR DESCRIPTION
**Pull request by milesmcc**
**Type of pull request:** product additions

**Related issues:** n/a

---

This PR brings in all of the nearly-correct product assessments from the old PrivacySpy site. All of the policies have some outstanding issue that prevented them from being merged in the original batch. (Note: all products that had no graded questions were removed.)

### CODE REVIEW

**Comment by doamatto** [comment]
Just making a bump notification so this doesn't get forgotten. If you let me know the appropriate way to, I can help convert the old data into the new format.

**Comment by milesmcc** [comment]
Thanks for the bump, @doamatto. You're right -- we've definitely let this slide. @ibarakaiev and I will get back to making pushes shortly...

**Comment by doamatto** [comment]
Bumping just so this pretty important PR gets done up.

**Comment by ibarakaiev** [comment]
@doamatto thanks for the bump. This is definitely on my mind; Miles has done his half and I'm long overdue on my side. I am entering finals in school so I will probably not get to this in the next three weeks but I promise I'll push after that :)

**Comment by doamatto** [comment]
Another friendly bump to make sure this doesn't get forgotten.

@ibarakaiev I'd gladly take some of the work off your back, if you'd like. Point me in the right direction and I've got you.

**Comment by milesmcc** [comment]
@doamatto I just added you to milesmcc/privacyspy so you should have push access to the merging repo.

**Comment by doamatto** [comment]
> there are plenty of policies that don't have pictures (usually for less-known product)

Alright, I'll do my best to see which are missing and bring the missing ones in

> I just added you to milesmcc/privacyspy so you should have push access to the merging repo.

Kudos, I'll start making additions when I next get a chance

**Comment by doamatto** [comment]
> there are plenty of policies that don't have pictures (usually for less-known product)

Alright, I'll do my best to see which are missing and bring the missing ones in

> I just added you to milesmcc/privacyspy so you should have push access to the merging repo.

Kudos, I'll start making additions when I next get a chance

Can one of you guys point me to where the old policies were, please and thank you; cc @milesmcc @ibarakaiev

**Comment by milesmcc** [comment]
@doamatto they are all already in the repo. They just need to be fixed so that 1) all the tests pass (`npm run test` iirc), 2) all the citations actually correspond to real quotes from the site, and 3) the citations justify the ratings.

**Comment by doamatto** [comment]
That should be everything fixed up. The only thing that needs to be done now is running image compression over the new images (some are a titbit over 30kb and fail tests because of it). We should be able to undraft this PR and ImgBot should run; that or install ImgBot on milesmcc/privacyspy to have it optimise the images there. 

I'll fix up the conflicts in the meantime.

cc @milesmcc @ibarakaiev

**Comment by milesmcc** [comment]
@doamatto images squashed. Let me know when these additional conflicts are fixed, then Igor and I can take a final look through and merge.

**Comment by doamatto** [comment]
Fixed the merge conflicts, but it appears the check is getting stuck on installing fsevents (which it can't; the check uses Linux, not macOS). It's possible `npm i --no-optional` might resolve the problem, but it seems to be a non-issue locally (even after cache clearning, rebuilding the lockfile, et cetera).

**Comment by doamatto** [comment]
@milesmcc You think you might know the remedy to this issue?

**Comment by milesmcc** [comment]
Taking a look at this now. Out of curiosity, what was the need for modifying package.json and adding those packages?

**Comment by milesmcc** [comment]
Tests now work @doamatto. Still a few icons that need smaller icons, though :(

**Comment by doamatto** [comment]
> Taking a look at this now. Out of curiosity, what was the need for modifying package.json and adding those packages?

When I was trying to run `npm test` or `gulp`, it would throw errors saying that a module was not found with that package name. Installing the packages seemed to remove the issue and continue to build. It's possible it was just a per-case scenario, but I'm not 100% sure.

**Comment by doamatto** [comment]
> Tests now work @doamatto. Still a few icons that need smaller icons, though :(

Alright, I'll manually shrink some down in a titbit to fit the criteria. Maybe we should find a way to tell ImgBot compress down to 30kB, if possible.

**Comment by doamatto** [comment]
@milesmcc I believe we are good to go 😃

**Comment by milesmcc** [comment]
Great. There are a few product labels that need improvement (ESPN, for example) but I can deal with that.

**Comment by doamatto** [comment]
Hey @milesmcc; wanted to see if you need some help with it since it's been a hot while.

**Comment by milesmcc** [comment]
Honestly, sure. Would you be able to go over the descriptions for the products and make sure that they aren't super weird? For example, right now the description for ESPN is quite corporate and sounds like it was copy-pasted right off their website. In general, we want descriptions to be informative, neutral, and useful to your average visitor. The current descriptions on the site provide a good example (in terms of both content and length).

**Comment by doamatto** [comment]
> Honestly, sure. Would you be able to go over the descriptions for the products and make sure that they aren't super weird? For example, right now the description for ESPN is quite corporate and sounds like it was copy-pasted right off their website. In general, we want descriptions to be informative, neutral, and useful to your average visitor. The current descriptions on the site provide a good example (in terms of both content and length).  

No problem; I'll try to get it done up by this Friday or so.

**Comment by milesmcc** [comment]
Cool, thanks! And no rush (obviously :)).

**Comment by doamatto** [comment]
@milesmcc Seems it went faster than I thought it would haha. You can check d72c02d for all the changes, as well as the git message for a more in-depth of what I did. I think it might be a smart idea to establish in the contribution guidelines that people should use non-vague or "biased" terminology when doing descriptions and contributing other content.

**Comment by doamatto** [comment]
@milesmcc Just checking to see when you reckon you might have a chance to look this PR over since it should be good to go (🤞)

**Pull request merged**
