### PR TITLE
ProtonMail and protonVPN

### PR DESCRIPTION
**Pull request by erotavlasme**
Type of pull request: product addition
Related issues: No

Adding new product: protonMail and protonVPN

### CODE REVIEW

**Comment by ibarakaiev** [comment]
Hi @erotavlasme, thanks for all your hard work! Unfortunately, I cannot review or merge your pull request as it seems to include too many products (while your title is only ProtonMail and ProtonVPN). Take a look at our [guide for how to contribute](https://privacyspy.org/contribute/). It also references a Github's [tutorial on pull requests](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests), in case you find that helpful. When you create a branch, it should be branched from our `master` branch, and each branch should include only _one_ product. Let me know if you have any questions!

**Comment by erotavlasme** [comment]
Hi @ibarakaiev I fixed it for all my pull requests. Tell me if you want that I do the same for [my first pull request](https://github.com/Politiwatch/privacyspy/pull/53) that includes many products.

**Comment by milesmcc** [comment]
@erotavlasme it looks like your new pull requests have the same issue:

image

What I really recommend you do is look at each product, create a new branch _based on the current PrivacySpy `master` branch_, and then create the files for only one product on that branch. When you submit a pull request, only commits related to the new product should show up. Note that it's _not possible_ to achieve the same effect by deleting files; we care quite a bit about the revision history.

We really appreciate all your hard work. Doing the PRs in the proper format just help us keep the repository and its history clean.

**Comment by erotavlasme** [comment]
Well, in theory it would be enough to take a look at the number of different files since I'm adding a new product. As you can see, now each branch has one product and two files (except two products in case of proton).
image
However, I will do it from scratch in order to move forward.

**Pull request closed without merging**
